### ISSUE TITLE
missing html files

### ISSUE THREAD

**Issue by ShaileshSarda** [soulextract/soulextract.com#2]
Can I have the HTML folder where I can run the project? Because I cloned the project repo and trying to run it locally but I am not able to run the project without HTML files?

**Comment by Sharaf-Mansour** [comment]
I think it runs on NodeJS.

**Comment by dnapier** [comment]
@ShaileshSarda This is pretty late, but this is a gatsbyjs project, I would read up on that topic. Specifically the page routing and layout sections.

**Comment by romelperez** [comment]
Hello! Since this is a [Gatsby](https://www.gatsbyjs.com) project, every single page is a JavaScript file inside the [`src/pages`](https://github.com/soulextract/soulextract.com/tree/master/src/pages) folder.

The project was made with the Gatsby v2 and I think it was Node.js v10 or 12 for it to run.
